### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by metabrozzpy** [ZiYang-xie/PyCAPTCHA#2]
This error occurred during train:

`requested resize to (60, 160) ((60, 160) elements in total), but the given tensor has a size of 3x60x160 (28800 elements). autograd's resize can only change the shape of a given tensor, while preserving the number of elements.`

**Comment by cxy-251** [comment]
I also met it. so I coment that line. 

And I mkdir checkpoint, changed default dir in arg_parsers.py.
Add ../ when generated dataset.
Gen pic without 'A'~'Z'.
The size of dataset is 1e4
epoch is 5

finally, acc is 0.347 in test. 

Over 98% accuracy, is that true?

**Comment by cxy-251** [comment]
> This error occurred during train:
> 
> `requested resize to (60, 160) ((60, 160) elements in total), but the given tensor has a size of 3x60x160 (28800 elements). autograd's resize can only change the shape of a given tensor, while preserving the number of elements.`

I also met it. so I coment that line.

And I mkdir checkpoint, changed default dir in arg_parsers.py.
Add ../ when generated dataset.
Gen pic without 'A'~'Z'.
The size of dataset is 1e4
epoch is 5

finally, acc is 0.347 in test.

Over 98% accuracy, is that true?

**Comment by ZiYang-xie** [comment]
BTW, this repo is definitely not the best practice to develop a CAPTCHA bypass app. A much more simple and effective hack is to load the CAPTCHA with `grey scale` and do some augmentation with pillow and feed it into `easyocr` or something like that to get better results. I think the performance of this repo can also be improved if converted the images into grey scale (just focus on the shape and ignore the unrelated color information). You can take this repo as a small project template or example to develop a simple deep_learning app with `torch_lightning`.
