### ISSUE TITLE
Error in absence of GPU

### ISSUE THREAD

**Issue by MohammadRezaArani** [ZiYang-xie/PyCAPTCHA#8]
I do not have a GPU on my PC and I want to run the training phase on my PC. There is no parameter to specify whether to use GPU or CPU.
Also, why not give a pre-trained network so that not everyone has to train the network independently?
Please help me with this issue.
Thanks
![Py_img](https://user-images.githubusercontent.com/35188471/232045909-542a0f5e-7206-478a-8f8a-4dac3d75da41.png)

**Comment by hypy13** [comment]
i trained the model 
if you need i can give it to you

**Comment by MohammadRezaArani** [comment]
I'd be happy if you could do that. TNX a bunch

**Comment by hypy13** [comment]
@MohammadRezaArani  so can you give me an email or something to send the files

**Comment by hypy13** [comment]
by the way if you want to train the model by CPU

you should edit launcher.py file line 26 and comment these arguments  in pl.Trainer function

  
```
trainer = pl.Trainer(
        deterministic=True,
        # gpus=args.gpus,
        # auto_select_gpus=True,
        precision=32,
        logger=tb_logger,
        # fast_dev_run=False,
        max_epochs=epoch,
        log_every_n_steps=50,
        stochastic_weight_avg=True
    )
```

**Comment by MohammadRezaArani** [comment]
Thanks, I'll check it out.

**Comment by ZiYang-xie** [comment]
> I do not have a GPU on my PC and I want to run the training phase on my PC. There is no parameter to specify whether to use GPU or CPU. Also, why not give a pre-trained network so that not everyone has to train the network independently? Please help me with this issue. Thanks ![Py_img](https://user-images.githubusercontent.com/35188471/232045909-542a0f5e-7206-478a-8f8a-4dac3d75da41.png)

Thanks hypy13. I believe your issue is largely resolved. Regarding the pretrained checkpoint, because CAPTCHA styles can vary in real-world applications, it may be better to train the model on your specific dataset to ensure optimal performance.
